### ISSUE TITLE
Implement WebSockets for widget events

### ISSUE THREAD

**Issue by dcgauld** [databoard/server#3]
Using WebSockets will allow us to update widgets in realtime. It will also allow widgets to request external APIs periodically in a server file and update their contents when needed (this will also bypass any cross-domain requests from the client).

@joshcroad What library do you think we should use? [Socket.io](http://socket.io/) seem to have recently pushed version 1.0, but am happy to try anything out.

**Comment by joshcroad** [comment]
I think we should use [Socket.IO](http://socket.io/) because they have release v1.0 so it's stable, it supports backward compatibility, and it's based on [ws](https://github.com/websockets/ws).
